name: java-system-config
filetype: java$
target: line
type: contains
advice: Review usage of environment variables and system properties and externalize. You can use springboot configuration or inject any per-service configuration settings into each service as environment variables. https://learn.microsoft.com/en-us/azure/developer/java/migration/migrate-spring-boot-to-azure-spring-apps#configure-per-service-secrets-and-externalized-settings
effort: 3
criticality: Warn
category: config
tags:
  - value: azure spring apps
  - value: config
patterns:
  - value: System.getenv(
  - value: System.getProperty(
  - value: System.setProperty(
  - value: System.setProperties(
